server:
  port: 8761

spring:
  application:
    name: eureka
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    