server:
  port: 9411

spring:
  application:
    name: zipkin-server


eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
