server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

    
zuul:
  routes:
    service-a:
      path: /**
      service-id: service-a
  